Obsolelo/vendas/urls.py
from django.urls import path
from django.contrib import admin
from vendas import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

app_name = 'vendas'

urlpatterns = [
    # Product URLs
    path('', views.HomePage.as_view(), name='homepage'),
    path('cadastro/', views.CadastroProduto.as_view(), name='cadastro_produto'),
    path("atualizar/<int:pk>/", views.AtualizaProduto.as_view(), name="atualizar_produto"),
    path("comprar/<int:pk>/", views.CompraProduto.as_view(), name="comprar_produto"),
    # User Registration URL
    path('registrar/', views.RegistraUsuario.as_view(), name='registrar_usuario'),
    path("accounts/profile/", LoginView.as_view(template_name='Vendas/login.html'), name='segundo_login'),
    # Login and Logout URLs
    path('login/', LoginView.as_view(template_name='Vendas/login.html',next_page = reverse_lazy('vendas:homepage')), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('vendas:homepage')), name='logout'),
    path("confirmaLogout/", views.ConfirmaLogout.as_view(), name="confirma_logout"),
]

Obsolelo/vendas/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.TextChoices):
    ELETRONICOS = 'ELE', 'Eletrônicos'
    ROUPAS = 'ROU', 'Roupas'
    LIVROS = 'LIV', 'Livros'
    MOVEIS = 'MOV', 'Móveis'
    OUTROS = 'OUT', 'Outros'

class Produto(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100,help_text="Nome do produto")
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Vendedor do produto")
    categoria = models.CharField(max_length=100,choices=Categoria.choices,default=Categoria.OUTROS,help_text="Categoria do produto")
    preco = models.DecimalField(max_digits=8, decimal_places=2,help_text="Preço do produto")
    foto = models.ImageField(upload_to='fotos_produtos/', null=True, blank=True, help_text="Foto do produto")
    descricao = models.TextField(help_text="Descrição do produto")

    def __str__(self):
        return f"{self.nome} - {self.vendedor.username}"

Obsolelo/vendas/forms.py
from django import forms
from vendas.models import Produto

class ProdutoModel2Form(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'categoria', 'preco', 'foto', 'descricao']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

Obsolelo/vendas/views.py
from django.shortcuts import render
from django.views import View
from vendas.forms import ProdutoModel2Form
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth import login, authenticate, logout


class HomePage(View):
    
    def get(self, request, *args, **kwargs):
        user_groups = request.user.groups.all() if request.user.is_authenticated else []
        vendas_produto = Produto.objects.all()
        categorias_choices = Categoria.choices
        categorias = []
        for categoria in categorias_choices:
            categorias.append(categoria[1])
        contexto = {'vendas_produto': vendas_produto, 'user_groups': user_groups, 'categorias': categorias}
        return render(request, 'vendas/homepage.html', contexto)


class CadastroProduto(View):
    
    def get(self, request, *args, **kwargs):
        contexto = {'form': ProdutoModel2Form()}
        return render(request, 'vendas/cadastroProduto.html', contexto)
    
    def post(self, request, *args, **kwargs):
        form = ProdutoModel2Form(request.POST)
        if form.is_valid():
            produto = form.save(commit=False)
            produto.vendedor = request.user
            produto.save()
            contexto = {
                'form': ProdutoModel2Form(),
                'mensagem': 'Produto cadastrado com sucesso!'
            }
            return render(request, 'vendas/cadastroProduto.html', contexto)
        contexto = {'form': form}
        return render(request, 'vendas/cadastroProduto.html', contexto)

class AtualizaProduto(View):
    
    def get(self, request, pk, *args, **kwargs):
        produto = Produto.objects.get(id=pk)
        form = ProdutoModel2Form(instance=produto)
        contexto = {'form': form}
        return render(request, 'vendas/atualizaProduto.html', contexto)
    
    def post(self, request, pk, *args, **kwargs):
        produto = get_object_or_404(Produto, id=pk)
        form = ProdutoModel2Form(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('vendas:homepage'))
        contexto = {'form': form}
        return render(request, 'vendas/atualizaProduto.html', contexto)

class CompraProduto(View):

    def get(self, request, pk, *args, **kwargs):
        produto = Produto.objects.get(id=pk)
        contexto = {'produto': produto}
        return render(request, 'vendas/comprarProduto.html', contexto)

    def post(self, request, pk, *args, **kwargs):
        produto = Produto.objects.get(id=pk)
        produto.delete()
        return HttpResponseRedirect(reverse_lazy('vendas:homepage'))
    
class RegistraUsuario(View):
    
    def get(self, request, *args, **kwargs):
        formulario = UserCreationForm()
        contexto = {'formulario': formulario}
        return render(request, 'vendas/registrarUsuario.html', contexto)

    def post(self, request, *args, **kwargs):
        formulario = UserCreationForm(request.POST)
        tipo_usuario = request.POST.get('tipo_usuario')
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect(reverse_lazy('vendas:homepage'))
        formulario = UserCreationForm()
        contexto = {'formulario': formulario}
        return render(request, 'vendas/registrarUsuario.html', contexto)
    
class ConfirmaLogout(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'vendas/logout.html')

Obsolelo/vendas/templates/Vendas/atualizaProduto.html
{% extends 'vendas/baseProduto.html' %}

{% block title %}Atualizar Produto{% endblock %}

{% block header %}Atualizar Produto{% endblock %}

{% block submitButton %}
      <button type="submit" class="btn btn-primary">Atualizar Produto</button>
{% endblock %}

Obsolelo/vendas/templates/Vendas/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'vendas/css/style.css' %}" />
    {% block extra_header %}{% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="d-flex justify-content-center align-items-center gap-2">
    <a href="{% url 'vendas:homepage' %}" class="btn btn-dark">Início</a>
    {% if user.is_authenticated %}
    <a href="{% url 'vendas:confirma_logout' %}" class="btn btn-dark">Logout</a>
    {% for group in request.user.groups.all %}
      {% if group.name == "Vendedor" %}
        <a href="{% url 'vendas:cadastro_produto' %}" class="btn btn-dark">Cadastrar Produto</a>
      {% endif %}
      {{ group.name }}
    {% endfor %}
    {% else %}
    <a href="{% url 'vendas:registrar_usuario' %}" class="btn btn-dark">Registrar</a>
    <a href="{% url 'vendas:login' %}" class="btn btn-dark">Login</a>
    {% endif %} 
    </div>
    {% block content %}{% endblock %}
  </body>
</html>

Obsolelo/vendas/templates/Vendas/baseProduto.html
{% extends "Vendas/base.html" %}
{% block title %}{% block titleProduto %}{% endblock %}{% endblock %}
{% block content %}
    <h1>{% block header %}{% endblock %}</h1>
    <form method="post" >
      {% csrf_token %}
      <table class="formulario">
        {{ form.as_table }}
      </table>
      {% block submitButton %}{% endblock %}
{% endblock %}

Obsolelo/vendas/templates/Vendas/cadastroProduto.html
{% extends 'vendas/baseProduto.html' %}

{% block title %}Cadastrar Produto{% endblock %}

{% block header %}Cadastrar Novo Produto{% endblock %}

{% block submitButton %}
      <button type="submit" class="btn btn-primary">Salvar Produto</button>
{% endblock %}

Obsolelo/vendas/templates/Vendas/comprarProduto.html
{% extends "Vendas/base.html" %}
{% block title %}Comprar Produto{% endblock %}
{% block content %}
    <div class="container">
      <h1>Comprar Produto</h1>
      <p>Você está prestes a comprar o seguinte produto:</p>
      <ul>
        <li>Nome: {{ produto.nome }}</li>
        <li>Preço: {{ produto.preco }}</li>
        <li>Vendedor: {{ produto.vendedor.username }}</li>
        <li>Descrição: {{ produto.descricao }}</li>
      </ul>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success mt-2">Confirmar Compra</button>
        <a href="{% url 'vendas:homepage' %}" class="btn btn-secondary mt-2">Voltar</a>
      </form>
    </div>
{% endblock %}

Obsolelo/vendas/templates/Vendas/homepage.html
{% extends "Vendas/base.html" %}
{% load static %}
{% block title %}Página Inicial{% endblock %}
{% block extra_header %}
    <link rel="stylesheet" href="{% static 'vendas/css/homepage.css' %}" />
{% endblock %}
{% block content %}
    <div class="container">
      <div class="barra-superior">
        <h1>Bem-vindo à Página Inicial</h1>
        <p>Esta é a página inicial do sistema de vendas.</p>
      </div>
      <div class="coluna-esquerda">
        <h2>Categorias</h2>
        <ul>
          {% for categoria in categorias %}
            <li>{{ categoria }}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="coluna-direita">
        <h2>Produtos</h2>
        <hr>
        <div class="produtos">
    <ul>
    {% for venda in vendas_produto %}
        <ul>
            <div>Produto: {{venda.nome}}</div>
            <div>Preço: {{venda.preco}}</div>
            <div>Vendedor: {{venda.vendedor.username}}</div>
            <div>Descrição: {{venda.descricao}}</div>
            <div class="botoes">
                <a href="{% url 'vendas:comprar_produto' pk=venda.id %}" class="btn btn-success">Comprar</a>
                <a href="{% url 'vendas:atualizar_produto' pk=venda.id %}" class="btn btn-primary">Atualizar Produto</a>
            <hr>
          </ul>
    {% empty %}
        <li>Nenhum produto encontrado.</li>
    {% endfor %}
    </ul>
</div>
      </div>
      <div class="rodape">
        <h1>Rodapé da página</h1>
    </div>
{% endblock %}

Obsolelo/vendas/templates/Vendas/login.html
{% extends "Vendas/base.html" %}
{% block title %}Página de Login{% endblock %}
{% block content %}

<div class="container mt-4">
  <h2>Login</h2>
  <div class="d-flex gap-2 mt-3">
    <form method="post">
      <table class="formulario">
        {% csrf_token %} 
        {{ form.as_table }}
      </table>
      <button type="submit" class="btn btn-primary mt-2">Login</button>
    </form>
  </div>
</div>
{% endblock %}

Obsolelo/vendas/templates/Vendas/logout.html
{% extends 'vendas/base.html' %}
{% block titulo %}Logout{% endblock %}
{% block content %}
<div class="container mt-4">
    <h2>Você tem certeza que deseja sair?</h2>

    <div class="d-flex gap-2 mt-3">
        <form method="post" action="{% url 'vendas:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mt-2">Sim, sair</button>
        </form>
        <a href="{% url 'vendas:homepage' %}" class="btn btn-secondary mt-2">Cancelar</a>
    </div>
</div>
{% endblock %}

Obsolelo/vendas/templates/Vendas/registrarUsuario.html
{% extends "Vendas/base.html" %}
{% block title %}Registro de Usuário{% endblock %}
{% block content %}
<div class="container mt-4">
  <h1>Registro de Usuário</h1>
  <div class="d-flex mt-3">
    <form method="post">
      {% csrf_token %}
      <table class="formulario">
        {{ formulario.as_table }}
        <th>Tipo de Usuário:</th>
        <td>
          <select name="tipo_usuario" required>
            <option value="comprador">Comprador</option>
            <option value="vendedor">Vendedor</option>
          </select>
        </td>
      </table>
      <input type="submit" value="Registrar" class="btn btn-primary mt-1" />
    </form>
  </div>
</div>
{% endblock %}