meusite/comprador/urls.py
from django.urls import path
from comprador import views

app_name = 'comprador'

urlpatterns = [

    path("<str:categoria>/<str:nome>/<int:pk>/", views.ProdutoIndividual.as_view(), name="produto_individual")
    
]

meusite/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from main import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.models import User
from django.urls import reverse_lazy

urlpatterns = [
    # Admin
    path("batata/", admin.site.urls),
    # Apps
    path("comprador/", include("comprador.urls")),
    path("vendedor/", include("vendedor.urls")),
    # main
    # Product URLs
    path("", views.HomePage.as_view(), name="homepage"),
    path("cadastro/", views.CadastroProduto.as_view(), name="cadastro_produto"),
    path(
        "atualizar/<int:pk>/", views.AtualizaProduto.as_view(), name="atualizar_produto"
    ),
    path(
        "produtos/<str:categoria>/",
        views.PaginaCategoria.as_view(),
        name="pagina_categoria",
    ),
    # User Registration URL
    path("registrar/", views.RegistraUsuario.as_view(), name="registrar_usuario"),
    path(
        "accounts/profile/",
        LoginView.as_view(template_name="main/login.html"),
        name="segundo_login",
    ),
    # Login and Logout URLs
    path(
        "login/",
        LoginView.as_view(
            template_name="main/login.html", next_page=reverse_lazy("homepage")
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(next_page=reverse_lazy("homepage")), name="logout"
    ),
    path("confirmaLogout/", views.ConfirmaLogout.as_view(), name="confirma_logout"),
    # Troca de Senha
    path(
        "trocaSenha/",
        PasswordChangeView.as_view(
            template_name="contas/password_change_form.html",
            success_url=reverse_lazy("troca_senha_feito"),
        ),
        name="troca_senha",
    ),
    path(
        "trocaSenhaFeito/",
        PasswordChangeDoneView.as_view(
            template_name="contas/password_change_done.html"
        ),
        name="troca_senha_feito",
    ),
    # path(
    #     "contas/editarPerfil/<int:pk>",
    #     UpdateView.as_view(
    #         template_name="contas/user_form.html",
    #         model=User,
    #         fields=["first_name", "last_name", "email"],
    #         success_url=reverse_lazy("homepage"),
    #     ),
    #     name="editar_perfil",
    # ),
    path(
        "contas/editarPerfilSeguro/<int:pk>/",
        views.MeuUpdateView.as_view(
            template_name="contas/user_form.html",
            model=User,
            fields=["first_name", "last_name", "email"],
            success_url=reverse_lazy("homepage"),
        ),
        name="editar_perfil_seguro",
    ),
    # Reset de Senha
    path(
        "contas/trocaSenha/",
        PasswordResetView.as_view(
            template_name="contas/password_reset_form.html",
            email_template_name="contas/password_reset_email.html",
            subject_template_name="contas/password_reset_subject.html",
            success_url=reverse_lazy("password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "contas/trocaSenhaFeito/",
        PasswordResetDoneView.as_view(
            template_name="contas/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "contas/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="contas/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "contas/password_reset_complete/",
        PasswordResetCompleteView.as_view(
            template_name="contas/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

meusite/vendedor/urls.py
from django.urls import path
from vendedor import views

app_name = 'vendedor'

urlpatterns = [
    path('meusprodutos/', views.MeusProdutos.as_view(), name='meus_produtos'),
    
]

meusite/main/forms.py
from django import forms
from produtos.models import Produto

class ProdutoModel2Form(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'categoria', 'preco', 'descricao']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

meusite/main/views.py
from django.shortcuts import render
from django.views import View
from .forms import ProdutoModel2Form
from produtos.models import Categoria, Produto
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView


class HomePage(View):
    
    def get(self, request, *args, **kwargs):
        user_groups = request.user.groups.all() if request.user.is_authenticated else []
        vendas_produto = Produto.objects.all()
        categorias_choices = Categoria.choices
        categorias = []
        for categoria in categorias_choices:
            categorias.append(categoria[1])
        contexto = {'vendas_produto': vendas_produto, 'user_groups': user_groups, 'categorias': categorias}
        return render(request, 'main/homepage.html', contexto)


class CadastroProduto(View):
    
    def get(self, request, *args, **kwargs):
        contexto = {'form': ProdutoModel2Form()}
        return render(request, 'main/cadastroProduto.html', contexto)
    
    def post(self, request, *args, **kwargs):
        form = ProdutoModel2Form(request.POST)
        if form.is_valid():
            produto = form.save(commit=False)
            produto.vendedor = request.user
            produto.save()
            contexto = {
                'form': ProdutoModel2Form(),
                'mensagem': 'Produto cadastrado com sucesso!'
            }
            return render(request, 'main/cadastroProduto.html', contexto)
        contexto = {'form': form}
        return render(request, 'main/cadastroProduto.html', contexto)

class AtualizaProduto(View):
    
    def get(self, request, pk, *args, **kwargs):
        produto = Produto.objects.get(id=pk)
        form = ProdutoModel2Form(instance=produto)
        contexto = {'form': form}
        return render(request, 'main/atualizaProduto.html', contexto)
    
    def post(self, request, pk, *args, **kwargs):
        produto = get_object_or_404(Produto, id=pk)
        form = ProdutoModel2Form(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('homepage'))
        contexto = {'form': form}
        return render(request, 'main/atualizaProduto.html', contexto)

class RegistraUsuario(View):
    
    def get(self, request, *args, **kwargs):
        formulario = UserCreationForm()
        contexto = {'formulario': formulario}
        return render(request, 'main/registrarUsuario.html', contexto)

    def post(self, request, *args, **kwargs):
        formulario = UserCreationForm(request.POST)
        tipo_usuario = request.POST.get('tipo_usuario')
        if formulario.is_valid():
            user = formulario.save()
            # Adicionar ao grupo baseado no tipo
            if tipo_usuario == 'vendedor':
                grupo_vendedor, created = Group.objects.get_or_create(name='Vendedor')
                user.groups.add(grupo_vendedor)
            elif tipo_usuario == 'comprador':
                grupo_comprador, created = Group.objects.get_or_create(name='Comprador')
                user.groups.add(grupo_comprador)

            return HttpResponseRedirect(reverse_lazy('homepage'))
        contexto = {'formulario': formulario}
        return render(request, 'main/registrarUsuario.html', contexto)
    
class ConfirmaLogout(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'main/logout.html')
    
class PaginaCategoria(View):

    def get(self, request, categoria, *args, **kwargs):
        '''
        Exibe a página de produtos por categoria.
        Parâmetros:
        - categoria: String com o rótulo da categoria selecionada.
        '''
        categorias_choices = Categoria.choices
        categoria_atual_label = None
        for cat in categorias_choices:
            if cat[1] == categoria:
                categoria_atual_label = cat[0]
                break
        produtos = Produto.objects.filter(categoria=categoria_atual_label)

        contexto = {'produtos': produtos, 'categorias': categorias_choices, 'categoria_atual_rotulo': categoria}
        return render(request, 'main/paginaCategoria.html', contexto)
    
class MeuUpdateView(UpdateView):
    def get(self, request, pk, *args, **kwargs):
        if request.user.id == pk:
            return super().get(request, pk, *args, **kwargs)
        else:
            return redirect('homepage')
    def post(self, request, pk, *args, **kwargs):
        return redirect('homepage')

meusite/main/templates/main/atualizaProduto.html
{% extends 'main/baseProduto.html' %}

{% block title %}Atualizar Produto{% endblock %}

{% block header %}Atualizar Produto{% endblock %}

{% block submitButton %}
      <button type="submit" class="btn btn-primary">Atualizar Produto</button>
{% endblock %}

meusite/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}" />
    {% block extra_header %}{% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="d-flex justify-content-center align-items-center gap-2">
    <a href="{% url 'homepage' %}" class="btn btn-dark">Início</a>
    {% if user.is_authenticated %}
    <a href="{% url 'troca_senha' %}" class="btn btn-dark">Trocar Senha</a>
    <a href="{% url 'editar_perfil_seguro' user.pk %}" class="btn btn-dark">Editar Perfil</a>
    <a href="{% url 'confirma_logout' %}" class="btn btn-dark">Logout</a>
    {% for group in user.groups.all %}
      {% if group.name == "Vendedor" %}
        <a href="{% url 'cadastro_produto' %}" class="btn btn-dark">Publicar Produto</a>
        <a href="{% url 'vendedor:meus_produtos' %}" class="btn btn-dark">Meus Produtos</a>
      {% endif %}
    {% endfor %}
    Logando como {{ user.username }}
    {% else %}
    <a href="{% url 'registrar_usuario' %}" class="btn btn-dark">Registrar</a>
    <a href="{% url 'login' %}" class="btn btn-dark">Login</a>
    {% endif %}
    </div>
    {% block content %}{% endblock %}
  </body>
</html>

meusite/main/templates/main/baseProduto.html
{% extends "main/base.html" %}
{% load static %}
{% block extra_header%} <link rel="stylesheet" href="{% static 'main/css/formulario.css' %}"/> {% endblock %}
{% block title %}{% block titleProduto %}{% endblock %}{% endblock %}
{% block content %}
    <h1>{% block header %}{% endblock %}</h1>
    
    <form method="post" >
      {% csrf_token %}
      <table class="formulario">
        {{ form.as_table }}
      </table>
      {% block submitButton %}{% endblock %}
{% endblock %}

meusite/main/templates/main/cadastroProduto.html
{% extends 'main/baseProduto.html' %}

{% block title %}Cadastrar Produto{% endblock %}

{% block header %}Cadastrar Novo Produto{% endblock %}

{% block submitButton %}
      <button type="submit" class="btn btn-primary">Salvar Produto</button>
{% endblock %}

meusite/main/templates/main/homepage.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Página Inicial{% endblock %}
{% block extra_header %}
    <link rel="stylesheet" href="{% static 'main/css/homepage.css' %}" />
{% endblock %}
{% block content %}
    <div class="container">
      <div class="barra-superior">
        <h1>Bem-vindo à Página Inicial</h1>
      </div>
      <div class="coluna-esquerda">
        <h2>Categorias</h2>
        <ul>
          {% for categoria in categorias %}
            <li><a href="{% url 'pagina_categoria' categoria=categoria %}">{{ categoria }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <div class="coluna-direita">
        <h2>Todos os Produtos</h2>
        <hr>
        <div class="produtos">
    <ul>
    {% for venda in vendas_produto %}
        <ul>
            <div>Produto: {{venda.nome}}</div>
            <div>Preço: R${{venda.preco}}</div>
            <div>Vendedor: {{venda.vendedor.username}}</div>
            <div>Descrição: {{venda.descricao}}</div>
            <div class="botoes">
                <a href="{% url 'comprador:produto_individual' pk=venda.id categoria=venda.categoria nome=venda.nome %}" class="btn btn-success">Comprar</a>
            </div>
            <hr>
          </ul>
    {% empty %}
        <li>Nenhum produto encontrado.</li>
    {% endfor %}
    </ul>
</div>
      </div>
      <div class="rodape"></div>
{% endblock %}

meusite/main/templates/main/login.html
{% extends "main/base.html" %}
{% block title %}Página de Login{% endblock %}
{% block content %}

<div class="container mt-4">
  <h2>Login</h2>
  <div class="d-flex gap-2 mt-3">
    <form method="post">
      <table class="formulario">
        {% csrf_token %} 
        {{ form.as_table }}
      </table>
      <button type="submit" class="btn btn-primary mt-2">Login</button>
      <a href="{% url 'password_reset' %}" class="btn btn-link mt-2">Esqueceu sua senha?</a>
    </form>
  </div>
</div>
{% endblock %}

meusite/main/templates/main/logout.html
{% extends 'main/base.html' %}
{% block titulo %}Logout{% endblock %}
{% block content %}
<div class="container mt-4">
    <h2>Você tem certeza que deseja sair?</h2>

    <div class="d-flex gap-2 mt-3">
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mt-2">Sim, sair</button>
        </form>
        <a href="{% url 'homepage' %}" class="btn btn-secondary mt-2">Cancelar</a>
    </div>
</div>
{% endblock %}

meusite/main/templates/main/paginaCategoria.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Produtos por Categoria{% endblock %}
{% block extra_header %}
    <link rel="stylesheet" href="{% static 'main/css/homepage.css' %}" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="barra-superior">
        <h1>Produtos em {{ categoria_atual_rotulo }}</h1>
    </div>
    <div class="coluna-esquerda">
        <h2>Categorias</h2>
        <ul>
          {% for categoria in categorias %}
            <li><a href="{% url 'pagina_categoria' categoria=categoria.1 %}">{{ categoria.1 }}</a></li>
          {% endfor %}
        </ul>
    </div>
    <div class="coluna-direita">
        <h2>Produtos em {{ categoria_atual_rotulo }}</h2>
        <hr>
        <div class="produtos">
            <ul>
                {% for produto in produtos %}
                    <ul>
                        <div>Produto: {{ produto.nome }}</div>
                        <div>Preço: R${{ produto.preco }}</div>
                        <div>Vendedor: {{ produto.vendedor.username }}</div>
                        <div>Descrição: {{ produto.descricao }}</div>
                        <div class="botoes">
                            <a href="{% url 'comprador:produto_individual' pk=produto.id categoria=produto.categoria nome=produto.nome %}" class="btn btn-success">Comprar</a>
                        </div>
                        <hr>
                    </ul>
                {% empty %}
                    <li>Nenhum produto encontrado nesta categoria.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="rodape"></div>
</div>
{% endblock %}

meusite/main/templates/main/registrarUsuario.html
{% extends "main/base.html" %}
{% load static %}
{% block extra_header%} <link rel="stylesheet" href="{% static 'main/css/formulario.css' %}"/> {% endblock %}
{% block title %}Registro de Usuário{% endblock %}
{% block content %}
<div class="container mt-4">
  <h1>Registro de Usuário</h1>
  <div class="d-flex mt-3">
    <form method="post">
      {% csrf_token %}
      <table class="formulario">
        {{ formulario.as_table }}
        <th>Tipo de Usuário:</th>
        <td>
          <select name="tipo_usuario" required>
            <option value="comprador">Comprador</option>
            <option value="vendedor">Vendedor</option>
          </select>
        </td>
      </table>
      <input type="submit" value="Registrar" class="btn btn-primary mt-1" />
    </form>
  </div>
</div>
{% endblock %}